In [28]:
import pandas as pd

CB = pd.read_csv(
    "/Users/cordiez/Documents/CompaniesHouse/OutputFiles/CB_2.csv", index_col=0
)
CB["Legal Name"] = CB["Legal Name"].fillna("")
MK = pd.read_csv(
    "/Users/cordiez/Documents/CompaniesHouse/OutputFiles/MK_geocoded.csv", index_col=0
)

# MK['CompanyNameCleared'].apply(lambda x:x.upper())
MK["CompanyNameCleared"] = MK["CompanyNameCleared"].apply(
    lambda x: "".join(e for e in x if e.isalnum())
    .upper()
    .replace("LTD", "")
    .replace("LIMITED", "")
)
CB["Legal Name"] = CB["Legal Name"].apply(
    lambda x: "".join(e for e in x if e.isalnum())
    .upper()
    .replace("LTD", "")
    .replace("LIMITED", "")
)

In [58]:
MK["CB Organization Name"] = None

In [64]:
known_comp_index = CB[
    CB["Legal Name"].isin(
        set(CB["Legal Name"].unique()).intersection(MK["CompanyNameCleared"])
    )
    == True
].index

In [86]:
pd.merge(
    CB,
    MK[["CompanyNameCleared", "Geocode_request"]],
    left_on="Legal Name",
    right_on="CompanyNameCleared",
    how="left",
)

,Organization Name,Industries,Headquarters Location,Description,CB Rank (Company),Headquarters Regions,Diversity Spotlight (US Only),Estimated Revenue Range,Operating Status,Founded Date,...,Transaction Name,Acquired by,Announced Date,Price,Acquisition Type,Acquisition Terms,Url,Legal Name,CompanyNameCleared,Geocode_request
0,HomeBase,"Home Decor, Internet, Retail, Retail Technology","Milton Keynes, Milton Keynes, United Kingdom",HomeBase is a home improvement and garden reta...,7404.0,NaN,NaN,$1B to $10B,Active,1979,...,HomeBase acquired by Hilco Capital,Hilco Capital,"May 25, 2018",NaN,Leveraged Buyout,NaN,https://www.crunchbase.com/organization/homeba...,HHGL,HHGL,"WITAN GATE HOUSE, 500-600 WITAN GATE, MILTON K..."
1,Envisics,"Augmented Reality, Automotive, Information Tec...","Milton Keynes, Milton Keynes, United Kingdom",Envisics develops a dynamic holography platfor...,8769.0,NaN,NaN,$1M to $10M,Active,"Jan 1, 2018",...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/envisics,ENVISICS,ENVISICS,"1A GARFORTH PLACE, KNOWLHILL, MILTON KEYNES, UK"
2,Africa Mobile Networks,"Communications Infrastructure, Consumer, Telec...","Milton Keynes, Milton Keynes, United Kingdom","Africa Mobile Networks is finances, builds, an...",14286.0,NaN,NaN,Less than $1M,Active,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/africa...,,NaN,NaN
3,SBD Automotive,"Automotive, Autonomous Vehicles, Consulting, C...","Milton Keynes, Milton Keynes, United Kingdom",SBD provides independent research and consulta...,37052.0,NaN,NaN,Less than $1M,Active,"Jul 14, 1997",...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/sbd,SBDAUTOMOTIVE,SBDAUTOMOTIVE,"12 DAVY AVENUE, KNOWLHILL, MILTON KEYNES, UK"
4,SOC.OS,"Cyber Security, Network Security, Software","Milton Keynes, Milton Keynes, United Kingdom",SOC.OS is a SaaS-based security alert investig...,37237.0,NaN,NaN,NaN,Active,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/soc-os,,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,phoneselectworld,"Consumer Electronics, E-Commerce, Hardware, So...","Milton Keynes, Milton Keynes, United Kingdom",Phones Elect World is one of the largest,1363153.0,NaN,NaN,NaN,Active,2005,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/phones...,,NaN,NaN
484,Adapt Global Group,"Furniture, Management Consulting, Service Indu...","Milton Keynes, Milton Keynes, United Kingdom",Adapt Global Group provides ergonomic office f...,1380993.0,NaN,NaN,$1M to $10M,Active,1996,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/adapt-...,,NaN,NaN
485,Badminton England,NaN,"Milton Keynes, Milton Keynes, United Kingdom",Badminton England is a organisation for all th...,1384329.0,NaN,NaN,NaN,Active,1893,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/badmin...,,NaN,NaN
486,CYSIAM,NaN,"Milton Keynes, Milton Keynes, United Kingdom",CYSIAM is a provider of managed cybersecurity ...,1385473.0,NaN,NaN,NaN,Active,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/cysiam,,NaN,NaN
487,Kinetic,"Catering, Events, Information Technology, Soft...","Milton Keynes, Milton Keynes, United Kingdom",Kinetic is a software solution provider for st...,NaN,NaN,NaN,$10M to $50M,Active,1998,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.crunchbase.com/organization/kineti...,KINETICSOLUTIONS,KINETICSOLUTIONS,"249 SILBURY BOULEVARD, , MILTON KEYNES, UK"

In [89]:
CB.sample(10)[["Organization Name", "Website"]]

              Organization Name                     Website
176                Managed 24/7           www.managed.co.uk
90                 Ikroh SEO UK               www.ikroh.com
186             Virtual Viewing   www.virtualviewing.co.uk/
224        DERMASPA NILAM PATEL         www.nilam-patel.com
206                     Pinders          www.pinders.co.uk/
393              Denbigh School            www.denbigh.net/
211                     Biznomy             www.biznomy.com
122  Blue Cube Creative Limited  www.bluecubecreative.co.uk
311                  Stadium MK          www.stadiummk.com/
173                   Reid & Co          www.reid-co.co.uk/

In [102]:
CB[CB["Phone Number"].isna() == False][["Website", "Organization Name"]].sample(8)

                           Website    Organization Name
59               www.goshfood.com/            Gosh Food
103     www.retinue-solutions.com/    Retinue Solutions
480  www.payperperformanceltd.com/  Pay Per Performance
307           www.s-digital.co.uk/            S-Digital
427             www.fernhoward.com          Fern Howard
286         www.strainsense.co.uk/          Strainsense
158             www.niftylift.com/            Niftylift
278           www.feedoptimise.com         Feedoptimise